### ISSUE TITLE
QM server for `qw11q` down

### ISSUE THREAD

**Issue by andrea-pasquale** [qiboteam/qibolab_platforms_qrc#170]
I'm getting the error message  `qm.exceptions.QmServerDetectionError: Failed to detect a QuantumMachines server. Tried connecting to 192.168.0.101:80`

Was the disconnection expected?

**Comment by alecandido** [comment]
> Was the disconnection expected?

I also tried, and it's not working any longer (it worked for me until yesterday evening). I don't believe it was expected, for sure not by me.

We can ask @stavros11, but maybe we should transfer the issue to https://github.com/qiboteam/qrccluster? (or in any case, we should ask someone in the lab - if you did it, share the update as soon as you have it, please)

**Comment by andrea-pasquale** [comment]
Apparently some electricians came to the lab and they needed to disconnect also the instruments attached to the XLD (The instruments should be done for around 1 hour). Let's see.

**Comment by stavros11** [comment]
Indeed, and it is still down. We could transfer the issue to the qrccluster repo, however one thing to note here is that there is very high chance that the sweetspots will need recalibration when the instruments are back online (based on previous experience with such shutdowns).

By the way, a quick way to check if it is a connection issue is to `ping 192.168.0.101` (or the relevant address), after connecting to a node (`srun -p qw11q --pty bash`). If there is no response, it should be a connection/lab/cluster problem.

**Comment by alecandido** [comment]
Issue solved, thanks both for monitoring. Shall we close?

> By the way, a quick way to check if it is a connection issue is to `ping 192.168.0.101` (or the relevant address), after connecting to a node (`srun -p qw11q --pty bash`). If there is no response, it should be a connection/lab/cluster problem.

@stavros11 you should have written `srun -p qw11q ping 192.168.0.101` :P

**Comment by andrea-pasquale** [comment]
The instruments are no longer reachable again...
