### ISSUE TITLE
Sweetspot not read in runcard by qblox

### ISSUE THREAD

**Issue by andrea-pasquale** [qiboteam/qibolab_platforms_qrc#36]
I'm trying to recalibrate `qw5q_gold` and I've seen that changing the sweetspot in the [runcard ](https://github.com/qiboteam/qibolab_platforms_qrc/blob/david/latest_qw5_gold_characterization/qw5q_gold.yml) does not actually change the sweetspot when running a flux experiment with qibocal.

I manage to change the sweetspot by modifying the offset in the `ClusterQCM_BB_Settings`
https://github.com/qiboteam/qibolab_platforms_qrc/blob/eddc17b7348a340e720ab34061503b6f76b40e64/qw5q_gold_qblox.py#L114
which were indeed the same as the sweetspot in the runcard.

To avoid setting this value twice I think that the create_function should read the sweetspot directly from the runcard instead of hardcoding them.
What do you think @rodolfocarobene, @stavros11 @DavidSarlle ?

**Comment by rodolfocarobene** [comment]
Is this a problem related to the sweepers type?

**Comment by DavidSarlle** [comment]
Definetly, it should be set from the runcard value.

**Comment by DavidSarlle** [comment]
we can set to 0 in the initial values for qcm_bb intruments_settings and, on create function we updated the offset with the runcard values... @andrea-pasquale are you already implementing it? I can do it if you want...

**Comment by andrea-pasquale** [comment]
I can implement it later today.
Regarding autocalibration if it reads the value from the runcard it will not be updated iteratively, right?

**Comment by DavidSarlle** [comment]
It will. The value is set through the port interface using the value that is in the runcard. The problem is only in the create.

**Comment by stavros11** [comment]
> I can implement it later today. Regarding autocalibration if it reads the value from the runcard it will not be updated iteratively, right?

Note sure if it is related, in the current qibolab main `platform.update` will change the value of the offset of the corresponding port

https://github.com/qiboteam/qibolab/blob/c5ff25ca19df2dd3d4aa3caeda584a55d5f03144/src/qibolab/platform.py#L197

This should update the instrument if things are working properly.

**Comment by andrea-pasquale** [comment]
> > I can implement it later today. Regarding autocalibration if it reads the value from the runcard it will not be updated iteratively, right?
> 
> Note sure if it is related, in the current qibolab main, if the sweetspot is updated then `platform.update` will change the value of the offset of the corresponding port
> 
> https://github.com/qiboteam/qibolab/blob/c5ff25ca19df2dd3d4aa3caeda584a55d5f03144/src/qibolab/platform.py#L197
> 
> This should update the instrument if things are working properly.

Thanks @stavros11 for the feedback. In my case I was running only the qubit flux dependence and I was modifying by hand the sweetspot value in the runcard. I've noticed that if I modify the value the sweep is still centered around the hardcoded values in the create function.

> `platform.setup` also loads the sweet spot from the runcard and sets it as the corresponding offset
> 
> https://github.com/qiboteam/qibolab/blob/c5ff25ca19df2dd3d4aa3caeda584a55d5f03144/src/qibolab/platform.py#L312

I see, then it is quite strange that it is behaving like that.

**Comment by DavidSarlle** [comment]
I have pushed changes. The value was not updated properly using the runcard value for the ss. Try now with https://github.com/qiboteam/qibolab/pull/518

Also I have removed the offset value from the initial config in the platform creation in 
https://github.com/qiboteam/qibolab_platforms_qrc/pull/34

to avoid duplications. Now  the driver is always using the value in the runcard

**Comment by rodolfocarobene** [comment]
I am also maintaining up to date the "qblox-review" PR, so that everything can be always tested completly

**Comment by andrea-pasquale** [comment]
Thanks @DavidSarlle.
It works as expected now.
