### ISSUE TITLE
Accessing TWPA parameters

### ISSUE THREAD

**Issue by andrea-pasquale** [qiboteam/qibolab_platforms_qrc#46]
I'm trying to access the TWPA frequency and power but I'm having some issues with `qw5q_gold`.
Using `get_lo_twpa_frequency` or  `get_lo_twpa_power`  I get the following error

```sh
AttributeError: 'NoneType' object has no attribute 'lo_power'
```
I think that it might be related to the fact that in the current main the twpa channels has a `None` port

https://github.com/qiboteam/qibolab_platforms_qrc/blob/a443a5875ff239d9792d2917d59d4eaf9f0d6925/qw5q_gold_qblox.py#L234

Any ideas on how to solve this @aorgazf @DavidSarlle @stavros11 ?
Keep in mind that this is blocking qiboteam/qibocal#478

**Comment by stavros11** [comment]
I think if you set the local oscillator to the channel
```py
channels["L4-26"].local_oscillator = twpa_pump
```
in the platform creation, it will solve the problem. As it is now, the twpa channel is not associated to any instrument because both the port and the local oscillator is `None`.
