### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by rodolfocarobene** [qiboteam/qibolab_platforms_qrc#6]
I was trying to push here a new branch, related to the new rfsoc driver and I got:

`remote: Permission to qiboteam/qibolab_platforms_qrc.git denied to rodolfocarobene.`

**Comment by stavros11** [comment]
Yes, see https://github.com/qiboteam/qibolab_platforms_qrc/pull/4#discussion_r1208993936

**Comment by scarrazza** [comment]
Fixed, thanks.
