### ISSUE TITLE
LO no longer connected to `qw5q_gold` platform

### ISSUE THREAD

**Issue by andrea-pasquale** [qiboteam/qibolab_platforms_qrc#68]
I'm using `qw5q_gold_qblox` in #65 and since 5 minutes ago I am getting the following error:
```
RuntimeError: Cannot establish connection to <qibolab.instruments.rohde_schwarz.
SGS100A object at 0x7f08bbed3610> instruments. Error captured: '[Errno 113] No r
oute to host'
```
Which lets me believe that probably the LO disconnected.
@aorgazf @PiergiorgioButtarini @DavidSarlle could you please check if the LO is properly connected?

**Comment by DavidSarlle** [comment]
@andrea-pasquale try now. Alvaro disconnected for a whhile because there was a problem with a ddifferent LO in order to access to it. Sorry

**Comment by andrea-pasquale** [comment]
Indeed, now it is working. Thanks.
