### ISSUE TITLE
Renew Github bot setup

### ISSUE THREAD

**Issue by Jacfomg** [qiboteam/qibolab_platforms_qrc#76]
This may improve timings with executing in hardware for the monitor.

**Comment by stavros11** [comment]
I believe the bot is already up-to-date, it is using Python venv and installing the latest qibolab and qibolab using poetry, so the versions of all dependencies should be following the corresponding lock files.

Regarding the RB timing issue, we could try to create a new environment under our user in the cluster and compare the times with the selfhosted. I will give a try when we are again able to use the instruments.

**Comment by Jacfomg** [comment]
Then I'm using the same I thing, also iqm device is operative.

**Comment by AleCandido** [comment]
Is this still an issue?

**Comment by AleCandido** [comment]
Maybe then just keep the issue and change title.

I suspect that given the workflow:
https://github.com/qiboteam/qibolab_platforms_qrc/blob/cdb2cc52e1ba4cc1563851042e69ef6ddd029f1a/.github/workflows/selfhosted.yml#L55-L72
there is no problem with the dependencies.

So, if something different is happening, it should be in the code executed (or the way the code is executed, even though it should be in the very same machine, I guess).

**Comment by alecandido** [comment]
The GitHub bot most likely will need to be reviewed completely, since quite some time has passed.

Let's close this, and reopen a new one whenever someone will need the bot again.
