### ISSUE TITLE
Add draft PR with every platform currently available

### ISSUE THREAD

**Issue by andrea-pasquale** [qiboteam/qibolab_platforms_qrc#81]
As discussed in a separate meeting it would be beneficial for everyone (and especially the middleware team) to have access to all QPUs currently available in the cluster in order to test and debug Qibocal/Qibolab.
I also suggest to remove from the current main all platforms that do not agree with the current configuration of chips/electronics.
Moreover, we don't need a perfectly calibrated runcard. For now opening a draft PR  (as already did by @aorgazf #80) with the correct `create`will be more than enough. Eventually each person responsible for the calibration can improve the calibration directly in those PRs.
Below I put a list of the missing runcard/platforms updated after the latest warm up (feel free to edit this as soon as the PR is opened).

- [x] qw5q_gold
- [ ] spinq10q
- [ ] iqm5q (fails when initializing instruments)
- [x] tii1q_b1 (runcard and platform working in main but chip not calibrated)
- [ ] any RFSoC related chip

**Comment by JavierSerranoGarcia** [comment]
The initial plan is to leave the tiiq_b1 connected to the RFSoC4x2 and connect one ZCU216 to one of the news tii2q. I have the platform and the runcard written but I want to check again everything is working before raising a PR

**Comment by andrea-pasquale** [comment]
Thanks @JavierSerranoGarcia. The RFSoC4x2 is not connected now, right?

**Comment by JavierSerranoGarcia** [comment]
Now RFSoC4x2 is connected and working.

**Comment by andrea-pasquale** [comment]
> Now RFSoC4x2 is connected and working.

I still see the board disconnected:
```sh
ConnectionRefusedError: [Errno 111] Connection refused
```
I am testing with the main branch. If the runcard in main is outdated feel free to open a new PR with the correct runcard.

**Comment by JavierSerranoGarcia** [comment]
I am doing a basic characterization, when done I will upload the runcard

**Comment by JavierSerranoGarcia** [comment]
Andrea, try to connect again.

**Comment by andrea-pasquale** [comment]
Thanks @JavierSerranoGarcia now the board is connected.

**Comment by andrea-pasquale** [comment]
Closing this as outdated

**Comment by stavros11** [comment]
> Closing this as outdated

Well, soon it may be relevant again...

**Comment by andrea-pasquale** [comment]
You are right...
Since this was done for the last warmup I was planning on opening a new one if the configurations arrive late, although I believe that the message should have already been received. Feel free to open it again if you prefer to keep it.
